name: Shell script

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
